import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#2c2c2c',
        'on-tertiary-container': '#001851',
        'on-primary-container': '#004050',
        'on-error-container': '#ffa8a3',
        surface: '#0E0E0E',
        'on-primary-fixed': '#002a35',
        'surface-container-highest': '#262626',
        'tertiary-dim': '#7999ff',
        'error-dim': '#d7383b',
        'surface-container-high': '#201f1f',
        background: '#0E0E0E',
        'on-secondary-container': '#f1f9ff',
        'on-primary-fixed-variant': '#004a5c',
        'surface-container': '#1a1919',
        secondary: '#17c0fd',
        'on-tertiary-fixed-variant': '#00318e',
        'inverse-surface': '#fcf8f8',
        'primary-fixed': '#00cffc',
        'surface-dim': '#0E0E0E',
        'secondary-dim': '#00b2ec',
        'surface-container-low': '#131313',
        'on-tertiary': '#00236d',
        tertiary: '#89a5ff',
        primary: '#69DAFF',
        error: '#ff716c',
        'tertiary-fixed': '#95adff',
        'on-error': '#490006',
        'on-background': '#ffffff',
        outline: '#777575',
        'tertiary-fixed-dim': '#819fff',
        'secondary-fixed': '#98daff',
        'surface-tint': '#69daff',
        'primary-dim': '#00c0ea',
        'on-surface-variant': '#ADAAAA',
        'on-tertiary-fixed': '#001345',
        'error-container': '#9f0519',
        'on-surface': '#ffffff',
        'inverse-primary': '#006880',
        'on-secondary-fixed-variant': '#005775',
        'secondary-container': '#006688',
        'on-secondary-fixed': '#00394e',
        'secondary-fixed-dim': '#6ecfff',
        'on-secondary': '#00374c',
        'outline-variant': '#494847',
        'tertiary-container': '#7696fd',
        'primary-container': '#00cffc',
        'inverse-on-surface': '#565554',
        'surface-variant': '#262626',
        'primary-fixed-dim': '#00c0ea',
        'on-primary': '#004a5d',
        'surface-container-lowest': '#000000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        label: ['var(--font-body)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
